############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "About"
url = "about/"
weight = 4

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5

[[main]]
weight = 2
name = "Projects"
hasChildren = true

[[main]]
parent = "Projects"
name = "Neutrino"
url = "neutrino/"

[[main]]
parent = "Projects"
name = "Getting Started"
url = "getting-started/"


# footer menu
# [[footer]]
# name = "Personal Site"
# url = "https://alexren.me/"
# weight = 1

# [[footer]]
# name = "Credits"
# url = "credits/"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
