############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

[[main]]
name = "Guide"
url = "introduction/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "About"
url = "about/"
weight = 5

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5

[[main]]
weight = 2
name = "Projects"
hasChildren = true

[[main]]
parent = "Projects"
name = "Neutrino"
url = "neutrino/"

[[main]]
weight = 3
name = "Resources"
hasChildren = true
url = "resources/"

[[main]]
parent = "Resources"
name = "Project Design"
url = "resources/project-design/"

# [[main]]
# parent = "Resources"
# name = "Biology"
# url = "resources/engineering"

# [[main]]
# parent = "Resources"
# name = "Physics"
# url = "resources/engineering"

# [[main]]
# parent = "Resources"
# name = "Economics"
# url = "resources/engineering"




# footer menu
# [[footer]]
# name = "Personal Site"
# url = "https://alexren.me/"
# weight = 1

# [[footer]]
# name = "Credits"
# url = "credits/"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
